In [70]:
import pandas as pd
import html5lib
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from tqdm import tqdm
import json
import scipy.stats as stats

In [71]:
def load_raw():
    dataframes=[]
    for k in tqdm(range(2001,2019)):
        for i in range(1,13):
            df = pd.read_html('./data/'+str(k)+'Y_'+str(i)+'M.xls',encoding='utf-8',header=0)
            dataframes.append(df[0])
    return dataframes

In [72]:
dataframes=load_raw()

100%|██████████| 18/18 [00:38<00:00,  4.38s/it]

In [73]:
df_nans=[]
for df in dataframes:
    df_nan=df[df.isna().any(1)]
    df_nan=df_nan.dropna(axis='columns')
    # 2007/12 2013/12 change
    df_nan.rename(columns={'類型代號':"基金名稱","基金統編":"基金規模","基金規模":"本月定時定額扣款筆數","單位淨值":"本月定時定額扣款人數","本月定時定額扣款筆數":"本月定時定額扣款金額"})
    df_nans.append(df_nan)

In [74]:
df_corrects=[]
df_filter = []
# for df in dataframes:
#     df_correct = df[~df.isna().any(1)]
#     df_corrects.append(df_correct)
for df in tqdm(dataframes):
    df.rename(columns={"基金規模(台幣)":"基金規模","單位淨值(台幣)":"單位淨值","本月定時定額扣款金額(台幣)":"本月定時定額扣款金額"}, inplace=True)
    df_correct = df[~df.isna().any(1)]
    df_filter = []
    for name in df_correct['基金名稱']:
        if ("中國" in name or "俄羅斯" in name or "巴西" in name or "印度" in name or "醫療" in name or "生技" in name) :
            if("中國信託" in name):
                continue
            filter1 = (df_correct['類型代號'] == "AA2")
            filter2 = (df_correct['類型代號'] == "2")
            filter3 = (df_correct['基金名稱'] == name)
            df_filter.append(df_correct[((filter1 | filter2) & filter3)])
    df_corrects.append(pd.concat(df_filter))
df_corrects[0]# 0=2001

100%|██████████| 216/216 [00:24<00:00,  1.80it/s]

   類型代號      基金統編    基金名稱       基金規模  單位淨值  本月定時定額扣款筆數  本月定時定額扣款人數  本月定時定額扣款金額
86    2  97990289  元大中國基金  436898521  6.54           8         8.0     63000.0

In [75]:
def plot_image(id):
    navs=[]
    money=[]
    num=[]
    people=[]
    scales=[]
    id = str(id)
    id = id.zfill(8)
    for i in range(0,2*12):
        try:
            navs.append(df_corrects[i][df_corrects[i]['基金統編']==id]['單位淨值'].values[0])
            money.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款金額'].values[0])
            num.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款筆數'].values[0])
            people.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款筆數'].values[0])
            scales.append(df_corrects[i][df_corrects[i]['基金統編']==id]['基金規模'].values[0])
        except:
            pass
    plt.plot(navs)
    plt.title('Unit net value')
    plt.ylabel('Value')
    plt.xlabel('Months')
    plt.show()
    plt.title('SIP value')
    plt.plot(money)
    plt.ylabel('Value')
    plt.xlabel('Months')
    plt.show()
    plt.title('SIP Number of records')
    plt.plot(num)
    plt.ylabel('Value')
    plt.xlabel('Months')
    plt.show()
    plt.title('SIP Number of people')
    plt.plot(people)
    plt.ylabel('Value')
    plt.xlabel('Months')
    plt.show()
    plt.title('SIP Scale')
    plt.plot(scales)
    plt.ylabel('Value')
    plt.xlabel('Months')
    plt.show()

## Function of calculating rising or falling

In [76]:
def monthFilter(month, length, data):
    subData = np.array(data[(month - (month % 6)) : (month + (5-(month % 6)) + 1)])
    value=(data[month] - np.mean(subData)) / np.std(subData)
    if(value> 1 or value < -1):
        return value
    else:
        return 0

## This function will get various people,aliveList,variations

In [77]:
def preprocessing():
    id_list = []
    id_temp = []
    aliveList=[]
    uid=[]
    upeople=[]
    peopleChinaList = []
    peopleIndiaList = []
    peopleBrazilList = []
    peopleRussiaList = []
    peopleMedicalList = []
    markMonthChinaList =[]
    markMonthIndiaList = []
    markMonthBrazilList = []
    markMonthRussiaList = []
    markMonthlMedicalList = []
    MonthChinaValue=[]
    MonthIndiaValue=[]
    MonthRussiaValue=[]
    MonthBrazilValue=[]
    for df in df_corrects:
        for filter_id in df['基金統編']:
#             id = str(filter_id)
#             id = id.zfill(8)
            id_temp.append(filter_id)
    id_list = list(set(id_temp))
    for id in id_list:
            isAlive = True
            navs=[]
            money=[]
            num=[]
            people=[]
            scales=[]
            name = ''
            isSaveList = []
            for i in range((17-3)*12 + 4,17*12 + 4):
                try:
                    name = df_corrects[i][df_corrects[i]['基金統編']==id]['基金名稱'].values[0]
                    navs.append(df_corrects[i][df_corrects[i]['基金統編']==id]['單位淨值'].values[0])
                    money.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款金額'].values[0])
                    num.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款筆數'].values[0])
                    people.append(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款人數'].values[0])
                    scales.append(df_corrects[i][df_corrects[i]['基金統編']==id]['基金規模'].values[0])
                    if(df_corrects[i][df_corrects[i]['基金統編']==id]['本月定時定額扣款人數'].values[0]) == 0 :
                        isAlive = False
                    if(i == 17*12 + 3 and isAlive):
                        aliveList.append(df_corrects[i][df_corrects[i]['基金統編']==id]['基金名稱'].values[0])
                        uid.append(df_corrects[i][df_corrects[i]['基金統編']==id]['基金統編'].values[0])
                
                except:
                    isAlive = False
                    navs.append(0)
                    money.append(0)
                    num.append(0)
                    people.append(0)
                    scales.append(0)
                    break
            funding={}
            funding
            if(isAlive):
                for i in range(0, len(people)):
                    if("中國" in name):
                        try:
                            peopleChinaList[i] += people[i]
                        except:
                            peopleChinaList.append(people[i])
                    elif("印度" in name):
                        try:
                            peopleIndiaList[i] += people[i]
                        except:
                            peopleIndiaList.append(people[i])
                    elif("巴西" in name):
                        try:
                            peopleBrazilList[i] += people[i]
                        except:
                            peopleBrazilList.append(people[i])
                    elif("俄羅斯" in name):
                        try:
                            peopleRussiaList[i] += people[i]
                        except:
                            peopleRussiaList.append(people[i])
                    else:
                        try:
                            peopleMedicalList[i] += people[i] 
                        except:
                            peopleMedicalList.append(people[i])
#                 plt.plot(navs)
#                 plt.title(id + 10*' ' +'Unit net value')
#                 plt.ylabel('Value')
#                 plt.xlabel('Months')
#                 plt.show()
#                 plt.title(id + 10*' ' +'SIP value')
#                 plt.plot(money)
#                 plt.ylabel('Value')
#                 plt.xlabel('Months')
#                 plt.show()
#                 plt.title(id + 10*' ' +'SIP Number of records')
#                 plt.plot(num)
#                 plt.ylabel('Value')
#                 plt.xlabel('Months')
#                 plt.show()
#                 plt.title(id + 10*' ' +'SIP Number of people')
#                 plt.plot(people)
#                 plt.ylabel('Value')
#                 plt.xlabel('Months')
#                 plt.show()
#                 plt.title(id + 10*' ' +'SIP Scale')
#                 plt.plot(scales)
#                 plt.ylabel('Value')
#                 plt.xlabel('Months')
#                 plt.show()

    # Calculate people and value
    
    china={}
    for i in range(0, len(peopleChinaList)):
        value=monthFilter(i, 6, peopleChinaList)
        if value!=0:
            markMonthChinaList.append(i)
            MonthChinaValue.append(value)
    china={
        'Month_Index':markMonthChinaList,
        'Value':MonthChinaValue
    }
    brazil={}
    for i in range(0, len(peopleBrazilList)):
        value=monthFilter(i, 6, peopleBrazilList)
        if value!=0:
            markMonthBrazilList.append(i)
            MonthBrazilValue.append(value)
    brazil={
        'Month_Index':markMonthBrazilList,
        'Value':MonthBrazilValue
    }
    for i in range(0, len(peopleIndiaList)):
        value=monthFilter(i, 6, peopleIndiaList)
        if value!=0:
            markMonthIndiaList.append(i)
            MonthIndiaValue.append(value)
    india={
        'Month_Index':markMonthBrazilList,
        'Value':MonthBrazilValue
    }
    for i in range(0, len(peopleRussiaList)):
        value=monthFilter(i, 6, peopleIndiaList)
        if value!=0:
            markMonthIndiaList.append(i)
            MonthIndiaValue.append(value)
    russia={
        'Month_Index':markMonthRussiaList,
        'Value':MonthRussiaValue
    }
    variation={
        'China':pd.DataFrame(china),
        'Brazil':pd.DataFrame(brazil),
        'India':pd.DataFrame(india),
        'Russia':pd.DataFrame(russia)
    }
    
#     for i in range(0, len(peopleMedicalList)):
#         if(monthFilter(i, 6, peopleMedicalList)):
#             markMonthlMedicalList.append(i)
#     plt.title('SIP Number of people in Medical')
#     plt.plot(peopleMedicalList)
#     plt.ylabel('Value')
#     plt.xlabel('Months')
#     plt.show()
    china_df=pd.DataFrame(china)
    dict={}
    start_date = "2016/04" 
    stop_date="2019/03"
    start=datetime.strptime(start_date,"%Y/%m")
    stop=datetime.strptime(stop_date,"%Y/%m")
    arr_smonth=[]
    while start<=stop:
        arr_smonth.append(start.strftime('%Y/%m')) # Return a string representing the date and time
        start = start +  relativedelta(months=1)
    percentage_c=[]
    percentage_b=[]
    percentage_r=[]
    percentage_i=[]
    for i in range(len(peopleChinaList)):
        total=peopleChinaList[i]+peopleIndiaList[i]+peopleRussiaList[i]+peopleBrazilList[i]
        percentage_c.append((peopleChinaList[i]/total)*100)
        percentage_b.append((peopleBrazilList[i]/total)*100)
        percentage_r.append((peopleRussiaList[i]/total)*100)
        percentage_i.append((peopleIndiaList[i]/total)*100)
        
        
    
    dict={
        'Date':arr_smonth,
        'China':peopleChinaList,
        'India':peopleIndiaList,
        'Russia':peopleRussiaList,
        'Brazil':peopleBrazilList,
        'China%':percentage_c,
        'India%':percentage_i,
        'Russia%':percentage_r,
        'Brazil%':percentage_b
    }
    alive={
        "name":aliveList,
        "uid":uid
    }
    
 
    peopleDF=pd.DataFrame(dict)
    aliveDF=pd.DataFrame(alive)
    return aliveList,aliveDF,variation,peopleDF

In [78]:
aliveList,aliveDF,varation ,people= preprocessing()
varation['China']

   Month_Index     Value
0            0 -1.856616
1            9 -2.054153
2           12  1.923390
3           17 -1.151120
4           20 -1.889533
5           22  1.122276
6           24 -1.470169
7           29  1.457625
8           33 -1.806295

In [79]:
people

,Date,China,India,Russia,Brazil,China%,India%,Russia%,Brazil%
0,2016/04,19451.0,2267.0,2104.0,3244.0,71.865071,8.375822,7.773590,11.985517
1,2016/05,22223.0,2247.0,2058.0,3210.0,74.729303,7.555989,6.920438,10.794270
2,2016/06,22482.0,2231.0,2040.0,3153.0,75.175550,7.460041,6.821374,10.543035
3,2016/07,22306.0,2442.0,1965.0,2971.0,75.144859,8.226654,6.619728,10.008759
4,2016/08,20813.0,2413.0,1881.0,2754.0,74.702990,8.660852,6.751373,9.884785
5,2016/09,21304.0,2360.0,1811.0,2597.0,75.890567,8.406954,6.451268,9.251211
6,2016/10,21493.0,2390.0,1738.0,2490.0,76.457614,8.502010,6.182633,8.857743
7,2016/11,21451.0,2314.0,1710.0,2375.0,77.023339,8.308797,6.140036,8.527828
8,2016/12,20909.0,2231.0,1663.0,2222.0,77.369103,8.255319,6.153562,8.222017
9,2017/01,17905.0,2046.0,1535.0,2062.0,76.036181,8.688636,6.518600,8.756582
10,2017/02,20907.0,2241.0,1565.0,2122.0,77.909447,8.351034,5.831936,7.907583
11,2017/03,20010.0,2170.0,1562.0,2099.0,77.435084,8.397508,6.044658,8.122751
12,2017/04,19725.0,2133.0,1526.0,2079.0,77.465342,8.376861,5.993009,8.164788
13,2017/05,19436.0,2099.0,1479.0,1995.0,77.716022,8.392979,5.913871,7.977128
14,2017/06,19333.0,2095.0,1487.0,1960.0,77.720603,8.422111,5.977889,7.879397
15,2017/07,19496.0,2102.0,1487.0,1903.0,78.021450,8.412038,5.950856,7.615656
16,2017/08,19473.0,2106.0,1474.0,1804.0,78.340105,8.472462,5.929919,7.257513
17,2017/09,19303.0,2093.0,1480.0,1801.0,78.222636,8.481582,5.997488,7.298294
18,2017/10,19040.0,2098.0,1453.0,1808.0,78.035985,8.598713,5.955162,7.410140
19,2017/11,18705.0,2113.0,1462.0,1799.0,77.681797,8.775281,6.071681,7.471241
20,2017/12,15852.0,1869.0,1404.0,1609.0,76.454133,9.014180,6.771486,7.760201
21,2018/01,17443.0,2097.0,1438.0,1778.0,76.652311,9.215152,6.319213,7.813324
22,2018/02,19449.0,2139.0,1447.0,1815.0,78.265594,8.607646,5.822938,7.303823
23,2018/03,18163.0,2102.0,1417.0,1797.0,77.358491,8.952681,6.035180,7.653648
24,2018/04,18314.0,2148.0,1413.0,1812.0,77.316672,9.068265,5.965297,7.649766
25,2018/05,18971.0,2143.0,1419.0,1838.0,77.842518,8.793238,5.822494,7.541750
26,2018/06,19810.0,2225.0,1432.0,1805.0,78.387148,8.804210,5.666350,7.142292
27,2018/07,20429.0,2306.0,1434.0,1777.0,78.736607,8.887690,5.526863,6.848840
28,2018/08,21093.0,2382.0,1432.0,1790.0,79.008877,8.922351,5.363899,6.704873
29,2018/09,21815.0,2476.0,1428.0,1778.0,79.335928,9.004619,5.193294,6.466160
30,2018/10,22991.0,2508.0,1425.0,1792.0,80.063379,8.733807,4.962390,6.240423
31,2018/11,23303.0,2492.0,1412.0,1764.0,80.435608,8.601705,4.873839,6.088847
32,2018/12,21735.0,2379.0,1381.0,1706.0,79.905151,8.746002,5.077019,6.271828
33,2019/01,20914.0,2267.0,1406.0,1692.0,79.584459,8.626660,5.350280,6.438601
34,2019/02,23256.0,2408.0,1398.0,1690.0,80.884808,8.375070,4.862270,5.877852
35,2019/03,23201.0,2324.0,1460.0,1668.0,80.972324,8.110844,5.095452,5.821380

In [80]:
newAliveList = []
for name in aliveList:
    if("新臺幣" in name):
        name = name.replace("新臺幣", "台幣")
    if("新台幣" in name):
        name = name.replace("新台幣", "台幣")
    if("台幣類型" in name):
        name = name.replace("台幣類型", "台幣")
    if("N" in name):
        name = name.replace("N", "N類型")
    if("-N類型" in name):
        name = name.replace("-N類型", "")
        name = name.replace("基金", "基金N類型")
    if("級別" in name):
        if("台幣" in name):
            name = name.replace("台幣級別", "(台幣)")
        if("人民幣" in name):
            name = name.replace("人民幣級別", "(人民幣)")
        if("美元" in name):
            name = name.replace("美元級別", "(美元)")
    if("-" in name):
        name = name.replace("-", "(", 1) + ")"
    if("人民幣類型" in name):
        name = name.replace("類型", "")
    if("兆豐國際中國A股基金(美金)" in name):
        name = name.replace("美金", "美元")
    if("安聯中國策略基金" in name):
        name = name + "(台幣)"
    if("台新中國精選中小基金" in name):
        name = name + "(台幣)"
    if("摩根中國A股基金" in name):
        if("摩根中國A股基金(美元)" in name):
            pass
        else:
            name = name + "(台幣)"
    if("瀚亞中國" in name):
        name = name.replace("中國", "中國A股")
    if("野村新興傘型基金之大俄羅斯基金" in name):
        name = name.replace("野村新興傘型基金之大俄羅斯基金", "野村大俄羅斯基金")
    if("野村雙印傘型基金之印度潛力基金" in name):
        name = name.replace("野村雙印傘型基金之印度潛力基金", "野村印度潛力基金")
    newAliveList.append(name)
# newAliveList

In [81]:
newAliveList

['兆豐國際中國A股基金(台幣)',
 '安聯全球生技趨勢基金(台幣)',
 '台新印度基金',
 '保德信全球醫療生化基金(台幣)',
 '安聯中國東協基金',
 '群益全球關鍵生技基金(台幣)',
 '日盛中國內需動力基金',
 '元大印度基金',
 '野村印度潛力基金',
 '安聯中國策略基金(台幣)',
 '兆豐國際中國A股基金(美元)',
 '瀚亞巴西基金',
 '野村全球生技醫療基金',
 '國泰中國內需增長基金(台幣)',
 '摩根中國亮點基金',
 '復華中國新經濟A股基金(台幣)',
 '野村中國機會基金',
 '群益中國新機會基金(台幣)',
 '野村大俄羅斯基金',
 '台新中國精選中小基金(台幣)',
 '野村巴西基金',
 '第一金中國世紀基金(台幣)',
 '德信中國精選成長基金']

In [82]:
# df_corrects[172][df_corrects[172]['基金名稱'] =='瀚亞巴西基金']['本月定時定額扣款人數']

In [83]:
aliveDF

               name        uid
0    兆豐國際中國A股基金(台幣)  38592074A
1    安聯全球生技趨勢基金-新臺幣  14693593A
2            台新印度基金   26322646
3   保德信全球醫療生化基金-新臺幣  14692638A
4          安聯中國東協基金   25680150
5    群益全球關鍵生技基金-新臺幣  38486708A
6        日盛中國內需動力基金   26323737
7            元大印度基金   25622390
8   野村雙印傘型基金之印度潛力基金   26278374
9          安聯中國策略基金   25589337
10   兆豐國際中國A股基金(美金)  38592074B
11           瀚亞巴西基金   25633559
12       野村全球生技醫療基金   48844514
13   國泰中國內需增長基金台幣級別  26317735A
14         摩根中國亮點基金   25627402
15  復華中國新經濟A股基金-新臺幣  42303511A
16         野村中國機會基金   25530596
17    群益中國新機會基金-新臺幣  38524463A
18  野村新興傘型基金之大俄羅斯基金   10306992
19       台新中國精選中小基金   25691213
20           野村巴西基金   25652008
21    第一金中國世紀基金-新臺幣  25620512A
22       德信中國精選成長基金   25689835

In [84]:
def country_classifier(newAliveList):
    country=dict()
    china_id=[]
    china_n=[]
    india_id=[]
    india_n=[]
    brazil_id=[]
    brazil_n=[]
    russia_id=[]
    russia_n=[]
    for funding,uid in zip(newAliveList['name'],newAliveList['uid']):
        if '中國' in funding:
            china_id.append(uid)
            china_n.append(funding)
        elif '巴西' in funding:
            brazil_id.append(uid)
            brazil_n.append(funding)
        elif '印度' in funding:
            india_id.append(uid)
            india_n.append(funding)
        elif '俄羅斯' in funding:
            russia_id.append(uid)
            russia_n.append(funding)
    country_id={
        'China':china_id,
        'Brazil':brazil_id,
        'India':india_id,
        'Russia':russia_id
    }
    country_n={
        'China':china_n,
        'Brazil':brazil_n,
        'India':india_n,
        'Russia':russia_n
        
    }
    return country_n,country_id

In [85]:
result_n,result_id=country_classifier(aliveDF)

In [86]:
def get_funding(dataframe):
    start_date = "2016/04" 
    stop_date="2019/03"
    start=datetime.strptime(start_date,"%Y/%m")
    stop=datetime.strptime(stop_date,"%Y/%m")
    arr_smonth=[]
    while start<=stop:
        arr_smonth.append(start.strftime('%Y/%m')) 
        start = start +  relativedelta(months=1)
    sip_people={}
    sip_people['Date']=arr_smonth
    for name,item in zip(dataframe['name'],dataframe['uid']):
        arr=[]
        for i in range(14*12+4,17*12+4):
            a=df_corrects[i][df_corrects[i]['基金統編']==item]['本月定時定額扣款人數'].values[0]
            arr.append(a)
        sip_people[item]=arr        
    return pd.DataFrame(sip_people)

In [87]:
result_n['China']

['兆豐國際中國A股基金(台幣)',
 '安聯中國東協基金',
 '日盛中國內需動力基金',
 '安聯中國策略基金',
 '兆豐國際中國A股基金(美金)',
 '國泰中國內需增長基金台幣級別',
 '摩根中國亮點基金',
 '復華中國新經濟A股基金-新臺幣',
 '野村中國機會基金',
 '群益中國新機會基金-新臺幣',
 '台新中國精選中小基金',
 '第一金中國世紀基金-新臺幣',
 '德信中國精選成長基金']

In [88]:
result_id['China']

['38592074A',
 '25680150',
 '26323737',
 '25589337',
 '38592074B',
 '26317735A',
 '25627402',
 '42303511A',
 '25530596',
 '38524463A',
 '25691213',
 '25620512A',
 '25689835']

In [89]:
def get_moneys(ids):
    sip_moneys={}
    for item in ids:
        sip_money=[]
        for i in range(14*12+4,17*12+4):
                    a=df_corrects[i][df_corrects[i]['基金統編']==item]['本月定時定額扣款金額'].values[0]
                    sip_money.append(a)
                    sip_moneys[item]=sip_money
    return pd.DataFrame(sip_moneys)

In [90]:
china_sip_money=get_moneys(result_id['China'])
for item in  result_id['China']:
    china_sip_money[item]= china_sip_money[item]/china_sip_money[item].max()
china_sip_money.columns = result_n['China']

In [91]:
brazil_sip_money=get_moneys(result_id['Brazil'])
for item in  result_id['Brazil']:
    brazil_sip_money[item]= brazil_sip_money[item]/brazil_sip_money[item].max()
brazil_sip_money.columns = result_n['Brazil']

In [92]:
russia_sip_money=get_moneys(result_id['Russia'])
for item in  result_id['Russia']:
    russia_sip_money[item]= russia_sip_money[item]/russia_sip_money[item].max()
russia_sip_money.columns = result_n['Russia']
# russia_sip_money

In [93]:
india_sip_money=get_moneys(result_id['India'])
for item in  result_id['India']:
    india_sip_money[item]= india_sip_money[item]/india_sip_money[item].max()
india_sip_money.columns = result_n['India']

# 計算相關係數--人數、價格、消息面

In [94]:

def get_country_emo():
    countrys=['china','brazil','russia','india']
    d_dict={}

    for country in countrys:
        with open('../emotion/'+country+'_emo.json', 'r') as read_file:
            arr=[]
            dict_data = json.load(read_file)
            arr= [values for key,values in  dict_data.items()]
            d_dict[country]=arr
    return pd.DataFrame(d_dict)
emo_df=get_country_emo()
emo_df=emo_df.fillna(value=0)

In [95]:

def get_money_people(id_data,name_data,people_dataframe):
    dfs=get_funding(people_dataframe)
    sip_money=get_moneys(id_data)
    a={}
    b={}
    df=dfs[id_data]
    for item in id_data:
        a[item]=sip_money[item]
        b[item]=df[item]
    correlation = {}
    for item in id_data:
        correlation[item]=stats.pearsonr(a[item],b[item])[0]
    cor_dataframe=pd.DataFrame(correlation,index=[0])
    cor_dataframe.columns=name_data
    return cor_dataframe

In [128]:
def get_money_shift_people(id_data,name_data,people_dataframe):
    dfs=get_funding(people_dataframe)
    sip_money=get_moneys(id_data)
    
    a={}
    b={}
    df=dfs[id_data]
    for item in id_data:
        a[item]=sip_money[item][1:] # header index
        b[item]=df[item][:-1] # object index
#     import ipdb;ipdb.set_trace()
    correlation = {}
    for item in id_data:
        correlation[item]=stats.pearsonr(a[item],b[item])[0]
    cor_dataframe=pd.DataFrame(correlation,index=[0])
    cor_dataframe.columns=name_data
    return cor_dataframe

In [ ]:
df_money_people=get_money_shift_people(result_id['China'],result_n['China'],aliveDF)

> <ipython-input-128-e8332b3dc2bf>(12)get_money_shift_people()
     11     import ipdb;ipdb.set_trace()
---> 12     correlation = {}
     13     for item in id_data:

ipdb> a
id_data = ['38592074A', '25680150', '26323737', '25589337', '38592074B', '26317735A', '25627402', '42303511A', '25530596', '38524463A', '25691213', '25620512A', '25689835']
name_data = ['兆豐國際中國A股基金(台幣)', '安聯中國東協基金', '日盛中國內需動力基金', '安聯中國策略基金', '兆豐國際中國A股基金(美金)', '國泰中國內需增長基金台幣級別', '摩根中國亮點基金', '復華中國新經濟A股基金-新臺幣', '野村中國機會基金', '群益中國新機會基金-新臺幣', '台新中國精選中小基金', '第一金中國世紀基金-新臺幣', '德信中國精選成長基金']
people_dataframe =                name        uid
0    兆豐國際中國A股基金(台幣)  38592074A
1    安聯全球生技趨勢基金-新臺幣  14693593A
2            台新印度基金   26322646
3   保德信全球醫療生化基金-新臺幣  14692638A
4          安聯中國東協基金   25680150
5    群益全球關鍵生技基金-新臺幣  38486708A
6        日盛中國內需動力基金   26323737
7            元大印度基金   25622390
8   野村雙印傘型基金之印度潛力基金   26278374
9          安聯中國策略基金   25589337
10   兆豐國際中國A股基金(美金)  38592074B
11           瀚亞巴西基金   25633559
12       野村全球生技醫療基金   48844514
13   國泰中國內需增長基金台幣級別  26317735A
14         摩根中國亮點基金   25627402
15  復華中國新經濟A股基金-新臺幣  42303511A
16         野村中國機會基金   25530596
17    群益中國新機會基金-新臺幣  38524463A
18  野村新興傘型基金之大俄羅斯基金   10306992
19       台新中國精選中小基金   25691213
20           野村巴西基金   25652008
21    第一金中國世紀基金-新臺幣  25620512A
22       德信中國精選成長基金   25689835
ipdb> print(a)
{'38592074A': 1      7151000.0
2      7001000.0
3      6636000.0
4      6340000.0
5      6201000.0
6      6346000.0
7      6302000.0
8      6153000.0
9      6113000.0
10     6056000.0
11     6056000.0
12     5941000.0
13     6025000.0
14     5859000.0
15     5939000.0
16     5960000.0
17     5777000.0
18     5889000.0
19     6126000.0
20     6128000.0
21     6049000.0
22     8800000.0
23     6140000.0
24     6186000.0
25     6435000.0
26     7113000.0
27     7666000.0
28     7977000.0
29     8782000.0
30     9686000.0
31    10359000.0
32    11070000.0
33    11684000.0
34    12767000.0
35    12390000.0
Name: 38592074A, dtype: float64, '25680150': 1     10710000.0
2     10382000.0
3     10012000.0
4      6222000.0
5     12728000.0
6      9874000.0
7      9092000.0
8      8285000.0
9      7782000.0
10     7498000.0
11     7407000.0
12     7330000.0
13     7458000.0
14     7444000.0
15     7748000.0
16     7907000.0
17     8090000.0
18     7955000.0
19     7722000.0
20     7663000.0
21     7608000.0
22     9972000.0
23     7463000.0
24     7396000.0
25     7684000.0
26     8242000.0
27     8386000.0
28     8631000.0
29     8973000.0
30     8838000.0
31     9004000.0
32     9819000.0
33    10572000.0
34    12434000.0
35     9738000.0
Name: 25680150, dtype: float64, '26323737': 1     4231000.0
2     5648000.0
3     4843000.0
4     4972000.0
5     5974000.0
6     3816000.0
7     4012000.0
8     3647000.0
9     3372000.0
10    3623000.0
11    3354000.0
12    3297000.0
13    3203000.0
14    3159000.0
15    3115000.0
16    3175000.0
17    3196000.0
18    3106000.0
19    2895000.0
20    2637000.0
21    2608000.0
22    2918000.0
23    2637000.0
24    2301000.0
25    2540000.0
26    2330000.0
27    2516000.0
28    2532000.0
29    2623000.0
30    2817000.0
31    2757000.0
32    2688000.0
33    2503000.0
34    2958000.0
35    2732000.0
Name: 26323737, dtype: float64, '25589337': 1      7704000.0
2      7622000.0
3      7787000.0
4      4994000.0
5      8828000.0
6      6679000.0
7      5973000.0
8      5694000.0
9      5017000.0
10     4803000.0
11     4717000.0
12     4585000.0
13     4501000.0
14     4576000.0
15     4574000.0
16     4564000.0
17     4561000.0
18     4563000.0
19     4455000.0
20     4501000.0
21     4475000.0
22     5750000.0
23     4296000.0
24     4169000.0
25     4114000.0
26     4392000.0
27     4464000.0
28     4500000.0
29     4851000.0
30     4971000.0
31     5050000.0
32     5917000.0
33     6478000.0
34    12235000.0
35    10527000.0
Name: 25589337, dtype: float64, '38592074B': 1     807820.0
2     950777.0
3     984628.0
4     612868.0
5     262416.0
6     330270.0
7     290650.0
8     236896.0
9     268606.0
10    242761.0
11    243399.0
12    239831.0
13    237302.0
14    240722.0
15    239214.0
16    238382.0
17    241903.0
18    229927.0
19    202067.0
20    187533.0
21    176544.0
22    308517.0
23    247485.0
24    250148.0
25    259010.0
26    259348.0
27    269713.0
28    199407.0
29    197010.0
30    222074.0
31    265946.0
32    304035.0
33    344329.0
34    355846.0
35    370951.0
Name: 38592074B, dtype: float64, '26317735A': 1     32129000.0
2     28142000.0
3     26424000.0
4     23634000.0
5     24347000.0
6     23074000.0
7     26104000.0
8     22697000.0
9     20707000.0
10    24359000.0
11    20744000.0
12    20242000.0
13    19088000.0
14    17965000.0
15    19074000.0
16    18674000.0
17    18732000.0
18    18086000.0
19    17786000.0
20    13095000.0
21    17057000.0
22    20464000.0
23    16320000.0
24    19161000.0
25    22821000.0
26    25960000.0
27    28450000.0
28    36989000.0
29    49482000.0
30    61023000.0
31    57479000.0
32    61506000.0
33    55820000.0
34    63595000.0
35    60836000.0
Name: 26317735A, dtype: float64, '25627402': 1     33192000.0
2     32608000.0
3     31606000.0
4     29569000.0
5     28061000.0
6     27088000.0
7     26540000.0
8     25966000.0
9     14146000.0
10    35587000.0
11    22956000.0
12    23692000.0
13    22449000.0
14    21873000.0
15    21704000.0
16    21255000.0
17    21043000.0
18    20834000.0
19    20512000.0
20    11054000.0
21    19700000.0
22    27982000.0
23    19123000.0
24    18839000.0
25    18774000.0
26    19022000.0
27    19650000.0
28    20890000.0
29    21840000.0
30    22979000.0
31    22522000.0
32    23672000.0
33    13337000.0
34    33992000.0
35    22773000.0
Name: 25627402, dtype: float64, '42303511A': 1      6085000.0
2      9280000.0
3      7532000.0
4      6889000.0
5      6643000.0
6      6724000.0
7      7774000.0
8      9499000.0
9      7748000.0
10     9944000.0
11     8665000.0
12     9301000.0
13     9083000.0
14    10015000.0
15    11906000.0
16     9796000.0
17     9680000.0
18    10452000.0
19    10874000.0
20     9936000.0
21     9688000.0
22    13950000.0
23    13424000.0
24    15327000.0
25    34196000.0
26    32447000.0
27    37429000.0
28    51469000.0
29    52145000.0
30    74504000.0
31    61392000.0
32    88301500.0
33    67011500.0
34    79550500.0
35    70678500.0
Name: 42303511A, dtype: float64, '25530596': 1     11729000.0
2     11397000.0
3     14390000.0
4      9703000.0
5      9465000.0
6      9363000.0
7      9047000.0
8     11448000.0
9      8256000.0
10     8652000.0
11     8079000.0
12     8163000.0
13     7811000.0
14     7817000.0
15     8120000.0
16     8096000.0
17     8168000.0
18     8483000.0
19     8540000.0
20     8096000.0
21     8064000.0
22     8442000.0
23     8391000.0
24     8363000.0
25     8473000.0
26     8855000.0
27    10056000.0
28    11401000.0
29    12293000.0
30    14857000.0
31    18779000.0
32    16059000.0
33    16203000.0
34    16274000.0
35    15862000.0
Name: 25530596, dtype: float64, '38524463A': 1     123091000.0
2      79074000.0
3      55910000.0
4      33438000.0
5      42083000.0
6      43819000.0
7      48951000.0
8      42034000.0
9      26452000.0
10     36331000.0
11     35072000.0
12     32211000.0
13     35222000.0
14     31803000.0
15     34875000.0
16     33155000.0
17     32390000.0
18     31819000.0
19     29457000.0
20     19453000.0
21     18011000.0
22     31710000.0
23     23195000.0
24     24837000.0
25     23285000.0
26     24863000.0
27     30310000.0
28     31085000.0
29     31197000.0
30     35091000.0
31     34570000.0
32     35054000.0
33     31191000.0
34     30585000.0
35     28393000.0
Name: 38524463A, dtype: float64, '25691213': 1     1674000.0
2     1741000.0
3     1591000.0
4     2013000.0
5     1856000.0
6     1320000.0
7     1444000.0
8     1420000.0
9     1301000.0
10    1324000.0
11    1228000.0
12    1237000.0
13    1219000.0
14    1151000.0
15    1110000.0
16    1372000.0
17    1480000.0
18    1500000.0
19    1427000.0
20    1360000.0
21     899000.0
22    1540000.0
23    1208000.0
24    1190000.0
25    1222000.0
26    1220000.0
27    1176000.0
28    1369000.0
29    1427000.0
30    1457000.0
31    1346000.0
32    1421000.0
33    1436000.0
34    1311000.0
35    1294000.0
Name: 25691213, dtype: float64, '25620512A': 1     60180836.0
2     55624682.0
3     50497819.0
4     45308401.0
5     49149176.0
6     44559208.0
7     46250247.0
8     40684090.0
9     31396854.0
10    44792313.0
11    39176821.0
12    35968070.0
13    34878653.0
14    34421851.0
15    35919004.0
16    36128504.0
17    37653018.0
18    38910794.0
19    35411483.0
20    30053886.0
21    29863801.0
22    41557681.0
23    33005415.0
24    33030690.0
25    31343125.0
26    30791346.0
27    30467260.0
28    29051733.0
29    27142684.0
30    27577823.0
31    27367060.0
32     9840421.0
33     9156275.0
34    15522165.0
35     8962973.0
Name: 25620512A, dtype: float64, '25689835': 1     455000.0
2     435000.0
3     432000.0
4     408000.0
5     392000.0
6     403000.0
7     399000.0
8     301000.0
9     329000.0
10    360000.0
11    360000.0
12    362000.0
13    371000.0
14    370000.0
15    362000.0
16    358000.0
17    356000.0
18    360000.0
19    362000.0
20    213000.0
21    368000.0
22    520000.0
23    371000.0
24    364000.0
25    384000.0
26    360000.0
27    357000.0
28    262000.0
29    262000.0
30    257000.0
31    259000.0
32    267000.0
33    267000.0
34    262000.0
35    259000.0
Name: 25689835, dtype: float64}

ipdb> print(b)
{'38592074A': 0      971.0
1      998.0
2     1016.0
3     1006.0
4      995.0
5      991.0
6     1000.0
7      999.0
8      978.0
9      971.0
10     966.0
11     949.0
12     938.0
13     940.0
14     933.0
15     937.0
16     936.0
17     925.0
18     935.0
19     941.0
20     921.0
21     935.0
22     937.0
23     927.0
24     929.0
25     953.0
26     989.0
27    1016.0
28    1065.0
29    1116.0
30    1178.0
31    1222.0
32    1252.0
33    1315.0
34    1353.0
Name: 38592074A, dtype: float64, '25680150': 0     1295.0
1     1293.0
2     1258.0
3     1215.0
4      964.0
5     1233.0
6     1245.0
7     1216.0
8     1192.0
9     1162.0
10    1155.0
11    1132.0
12    1110.0
13    1099.0
14    1091.0
15    1096.0
16    1107.0
17    1108.0
18    1098.0
19    1093.0
20    1075.0
21    1070.0
22    1083.0
23    1070.0
24    1065.0
25    1063.0
26    1096.0
27    1111.0
28    1112.0
29    1127.0
30    1134.0
31    1139.0
32    1157.0
33    1194.0
34    1251.0
Name: 25680150, dtype: float64, '26323737': 0     548.0
1     567.0
2     575.0
3     568.0
4     556.0
5     545.0
6     536.0
7     533.0
8     525.0
9     494.0
10    515.0
11    511.0
12    498.0
13    488.0
14    498.0
15    493.0
16    484.0
17    487.0
18    463.0
19    437.0
20    425.0
21    415.0
22    426.0
23    420.0
24    398.0
25    404.0
26    394.0
27    396.0
28    398.0
29    408.0
30    410.0
31    410.0
32    409.0
33    392.0
34    406.0
Name: 26323737, dtype: float64, '25589337': 0     560.0
1     619.0
2     652.0
3     689.0
4     589.0
5     722.0
6     712.0
7     696.0
8     689.0
9     645.0
10    630.0
11    612.0
12    590.0
13    585.0
14    588.0
15    583.0
16    588.0
17    575.0
18    579.0
19    553.0
20    552.0
21    550.0
22    544.0
23    529.0
24    523.0
25    529.0
26    540.0
27    542.0
28    544.0
29    551.0
30    566.0
31    557.0
32    582.0
33    605.0
34    827.0
Name: 25589337, dtype: float64, '38592074B': 0     15.0
1     14.0
2     12.0
3     12.0
4     11.0
5     11.0
6     11.0
7     11.0
8      9.0
9     10.0
10     9.0
11    10.0
12    10.0
13    10.0
14    10.0
15    10.0
16    10.0
17    10.0
18    10.0
19     9.0
20     9.0
21     8.0
22     9.0
23     9.0
24     9.0
25    10.0
26    11.0
27    10.0
28    11.0
29     9.0
30    11.0
31    14.0
32    16.0
33    16.0
34    19.0
Name: 38592074B, dtype: float64, '26317735A': 0     3413.0
1     3635.0
2     3590.0
3     3564.0
4     3382.0
5     3375.0
6     3381.0
7     3363.0
8     3269.0
9     3166.0
10    3288.0
11    3175.0
12    3153.0
13    3069.0
14    3016.0
15    3057.0
16    3038.0
17    2978.0
18    2981.0
19    2934.0
20    2453.0
21    2883.0
22    2895.0
23    2798.0
24    2909.0
25    3051.0
26    3278.0
27    3530.0
28    3682.0
29    4066.0
30    4590.0
31    4717.0
32    5067.0
33    5079.0
34    5425.0
Name: 26317735A, dtype: float64, '25627402': 0     4013.0
1     4164.0
2     4126.0
3     4066.0
4     3917.0
5     3867.0
6     3844.0
7     3800.0
8     3708.0
9     2330.0
10    3646.0
11    3495.0
12    3473.0
13    3405.0
14    3351.0
15    3370.0
16    3324.0
17    3292.0
18    3260.0
19    3220.0
20    2031.0
21    3159.0
22    3185.0
23    3075.0
24    3066.0
25    3060.0
26    3070.0
27    3073.0
28    3114.0
29    3178.0
30    3228.0
31    3217.0
32    3223.0
33    2144.0
34    3315.0
Name: 25627402, dtype: float64, '42303511A': 0       12.0
1      431.0
2      604.0
3      643.0
4      643.0
5      662.0
6      704.0
7      726.0
8      760.0
9      770.0
10     859.0
11     890.0
12     907.0
13     918.0
14     948.0
15     998.0
16    1053.0
17    1067.0
18    1081.0
19    1107.0
20    1063.0
21    1085.0
22    1259.0
23    1296.0
24    1436.0
25    1875.0
26    2428.0
27    2804.0
28    3175.0
29    3475.0
30    3810.0
31    3963.0
32    4741.0
33    4886.0
34    5274.0
Name: 42303511A, dtype: float64, '25530596': 0     1540.0
1     1558.0
2     1503.0
3     1505.0
4     1436.0
5     1406.0
6     1386.0
7     1365.0
8     1365.0
9     1290.0
10    1285.0
11    1259.0
12    1243.0
13    1231.0
14    1233.0
15    1244.0
16    1235.0
17    1233.0
18    1219.0
19    1220.0
20    1216.0
21    1215.0
22    1223.0
23    1199.0
24    1201.0
25    1222.0
26    1259.0
27    1288.0
28    1343.0
29    1423.0
30    1557.0
31    1657.0
32    1685.0
33    1746.0
34    1794.0
Name: 25530596, dtype: float64, '38524463A': 0     2593.0
1     3191.0
2     3384.0
3     3322.0
4     2749.0
5     3101.0
6     3241.0
7     3343.0
8     3321.0
9     2721.0
10    3162.0
11    3077.0
12    2984.0
13    2893.0
14    2910.0
15    2905.0
16    2872.0
17    2796.0
18    2698.0
19    2580.0
20    2077.0
21    2061.0
22    2455.0
23    2350.0
24    2317.0
25    2330.0
26    2405.0
27    2492.0
28    2526.0
29    2554.0
30    2707.0
31    2762.0
32    2886.0
33    2854.0
34    2826.0
Name: 38524463A, dtype: float64, '25691213': 0     176.0
1     183.0
2     179.0
3     167.0
4     170.0
5     169.0
6     176.0
7     187.0
8     183.0
9     180.0
10    181.0
11    172.0
12    167.0
13    169.0
14    167.0
15    159.0
16    162.0
17    169.0
18    166.0
19    161.0
20    159.0
21    135.0
22    162.0
23    158.0
24    160.0
25    157.0
26    154.0
27    154.0
28    156.0
29    158.0
30    159.0
31    160.0
32    161.0
33    160.0
34    160.0
Name: 25691213, dtype: float64, '25620512A': 0     4285.0
1     5539.0
2     5556.0
3     5523.0
4     5377.0
5     5200.0
6     5233.0
7     5188.0
8     4886.0
9     4139.0
10    5181.0
11    4698.0
12    4622.0
13    4598.0
14    4557.0
15    4614.0
16    4635.0
17    4633.0
18    4521.0
19    4423.0
20    3845.0
21    3896.0
22    5240.0
23    4301.0
24    4269.0
25    4285.0
26    4155.0
27    3982.0
28    3937.0
29    3721.0
30    3613.0
31    3456.0
32     527.0
33     494.0
34     578.0
Name: 25620512A, dtype: float64, '25689835': 0     30.0
1     31.0
2     27.0
3     26.0
4     24.0
5     22.0
6     24.0
7     24.0
8     24.0
9     27.0
10    30.0
11    30.0
12    30.0
13    31.0
14    31.0
15    30.0
16    29.0
17    30.0
18    29.0
19    27.0
20    26.0
21    31.0
22    31.0
23    31.0
24    32.0
25    32.0
26    31.0
27    31.0
28    30.0
29    29.0
30    28.0
31    29.0
32    29.0
33    29.0
34    28.0
Name: 25689835, dtype: float64}

In [96]:
def get_news_people(emo_df,id_data,name_data,people_dataframe):
    percentage=emo_df
    dfs=get_funding(people_dataframe)
    b={}
    df=dfs[id_data]
    correlation={}
    for item in id_data:
        b[item]=df[item]
    for item in id_data:
        correlation[item]=stats.pearsonr(percentage,b[item])[0]
    cor_dataframe=pd.DataFrame(correlation,index=[0])
    cor_dataframe.columns=name_data
    return cor_dataframe

In [97]:
def get_news_money(emo_df,id_data,name_data):
    sip_money=get_moneys(id_data)
    percentage=emo_df
    a={}
    for item in id_data:
        a[item]=sip_money[item]
    correlation = {}
    for item in id_data:
        correlation[item]=stats.pearsonr(percentage,a[item])[0]
    
    cor_dataframe=pd.DataFrame(correlation,index=[0])
    
    cor_dataframe.columns=name_data
    return cor_dataframe

In [98]:
def merge(df_money_people,df_news_people,df_news_money):
    df_all=pd.concat([df_money_people,df_news_people,df_news_money],axis=0, ignore_index=True)
    df_all=df_all.rename(index={0:"money_people",1:"news_people",2:"news_money"})
    return df_all

In [101]:
df_money_people=get_money_people(result_id['China'],result_n['China'],aliveDF)
df_news_people=get_news_people(emo_df['china'],result_id['China'],result_n['China'],aliveDF)
df_news_money=get_news_money(emo_df['china'],result_id['China'],result_n['China'])
china=merge(df_money_people,df_news_people,df_news_money)

In [102]:
russia_money_people=get_money_people(result_id['Russia'],result_n['Russia'],aliveDF)
russia_news_money=get_news_money(emo_df['russia'],result_id['Russia'],result_n['Russia'])
russia_news_people=get_news_people(emo_df['russia'],result_id['Russia'],result_n['Russia'],aliveDF)
russia=merge(russia_money_people,russia_news_people,russia_news_money)

In [103]:
brazil_money_people=get_money_people(result_id['Brazil'],result_n['Brazil'],aliveDF)
brazil_news_money=get_news_money(emo_df['brazil'],result_id['Brazil'],result_n['Brazil'])
brazil_news_people=get_news_people(emo_df['brazil'],result_id['Brazil'],result_n['Brazil'],aliveDF)
brazil=merge(brazil_money_people,brazil_news_people,brazil_news_money)

In [104]:
india_money_people=get_money_people(result_id['India'],result_n['India'],aliveDF)
india_news_money=get_news_money(emo_df['india'],result_id['India'],result_n['India'])
india_news_people=get_news_people(emo_df['india'],result_id['India'],result_n['India'],aliveDF)
india=merge(india_money_people,india_news_money,india_news_people)

In [114]:
import os
os.makedirs("correlation", exist_ok=True)
f = open('./correlation/china_corr.json','w')
f.write(china.to_json(force_ascii=False))
f.close()

In [115]:
f = open('./correlation/russia_corr.json','w')
f.write(russia.to_json(force_ascii=False))
f.close()

In [116]:
f = open('./correlation/india_corr.json','w')
f.write(india.to_json(force_ascii=False))
f.close()

In [117]:
f = open('./correlation/brazil_corr.json','w')
f.write(india.to_json(force_ascii=False))
f.close()

In [36]:
df=get_funding(aliveDF)
df_china=df[result_id['China']]
df_china.columns = [result_n['China']]
df_china
print(df_china.to_json(force_ascii=False))
f = open('china.json','w')
f.write(df_china.to_json(force_ascii=False))
f.close()

{"["日盛中國內需動力基金"]":{"0":548,"1":567,"2":575,"3":568,"4":556,"5":545,"6":536,"7":533,"8":525,"9":494,"10":515,"11":511,"12":498,"13":488,"14":498,"15":493,"16":484,"17":487,"18":463,"19":437,"20":425,"21":415,"22":426,"23":420,"24":398,"25":404,"26":394,"27":396,"28":398,"29":408,"30":410,"31":410,"32":409,"33":392,"34":406,"35":395},"["野村中國機會基金"]":{"0":1540,"1":1558,"2":1503,"3":1505,"4":1436,"5":1406,"6":1386,"7":1365,"8":1365,"9":1290,"10":1285,"11":1259,"12":1243,"13":1231,"14":1233,"15":1244,"16":1235,"17":1233,"18":1219,"19":1220,"20":1216,"21":1215,"22":1223,"23":1199,"24":1201,"25":1222,"26":1259,"27":1288,"28":1343,"29":1423,"30":1557,"31":1657,"32":1685,"33":1746,"34":1794,"35":1811},"["第一金中國世紀基金-新臺幣"]":{"0":4285,"1":5539,"2":5556,"3":5523,"4":5377,"5":5200,"6":5233,"7":5188,"8":4886,"9":4139,"10":5181,"11":4698,"12":4622,"13":4598,"14":4557,"15":4614,"16":4635,"17":4633,"18":4521,"19":4423,"20":3845,"21":3896,"22":5240,"23":4301,"24":4269,"25":4285,"26":4155,"27":3982,"28":3937,"29":3721,"30":3613,"31":3456,"32":527,"33":494,"34":578,"35":493},"["復華中國新經濟A股基金-新臺幣"]":{"0":12,"1":431,"2":604,"3":643,"4":643,"5":662,"6":704,"7":726,"8":760,"9":770,"10":859,"11":890,"12":907,"13":918,"14":948,"15":998,"16":1053,"17":1067,"18":1081,"19":1107,"20":1063,"21":1085,"22":1259,"23":1296,"24":1436,"25":1875,"26":2428,"27":2804,"28":3175,"29":3475,"30":3810,"31":3963,"32":4741,"33":4886,"34":5274,"35":5406},"["德信中國精選成長基金"]":{"0":30,"1":31,"2":27,"3":26,"4":24,"5":22,"6":24,"7":24,"8":24,"9":27,"10":30,"11":30,"12":30,"13":31,"14":31,"15":30,"16":29,"17":30,"18":29,"19":27,"20":26,"21":31,"22":31,"23":31,"24":32,"25":32,"26":31,"27":31,"28":30,"29":29,"30":28,"31":29,"32":29,"33":29,"34":28,"35":28},"["安聯中國東協基金"]":{"0":1295,"1":1293,"2":1258,"3":1215,"4":964,"5":1233,"6":1245,"7":1216,"8":1192,"9":1162,"10":1155,"11":1132,"12":1110,"13":1099,"14":1091,"15":1096,"16":1107,"17":1108,"18":1098,"19":1093,"20":1075,"21":1070,"22":1083,"23":1070,"24":1065,"25":1063,"26":1096,"27":1111,"28":1112,"29":1127,"30":1134,"31":1139,"32":1157,"33":1194,"34":1251,"35":1225},"["摩根中國亮點基金"]":{"0":4013,"1":4164,"2":4126,"3":4066,"4":3917,"5":3867,"6":3844,"7":3800,"8":3708,"9":2330,"10":3646,"11":3495,"12":3473,"13":3405,"14":3351,"15":3370,"16":3324,"17":3292,"18":3260,"19":3220,"20":2031,"21":3159,"22":3185,"23":3075,"24":3066,"25":3060,"26":3070,"27":3073,"28":3114,"29":3178,"30":3228,"31":3217,"32":3223,"33":2144,"34":3315,"35":3257},"["安聯中國策略基金"]":{"0":560,"1":619,"2":652,"3":689,"4":589,"5":722,"6":712,"7":696,"8":689,"9":645,"10":630,"11":612,"12":590,"13":585,"14":588,"15":583,"16":588,"17":575,"18":579,"19":553,"20":552,"21":550,"22":544,"23":529,"24":523,"25":529,"26":540,"27":542,"28":544,"29":551,"30":566,"31":557,"32":582,"33":605,"34":827,"35":895},"["國泰中國內需增長基金台幣級別"]":{"0":3413,"1":3635,"2":3590,"3":3564,"4":3382,"5":3375,"6":3381,"7":3363,"8":3269,"9":3166,"10":3288,"11":3175,"12":3153,"13":3069,"14":3016,"15":3057,"16":3038,"17":2978,"18":2981,"19":2934,"20":2453,"21":2883,"22":2895,"23":2798,"24":2909,"25":3051,"26":3278,"27":3530,"28":3682,"29":4066,"30":4590,"31":4717,"32":5067,"33":5079,"34":5425,"35":5365},"["兆豐國際中國A股基金(台幣)"]":{"0":971,"1":998,"2":1016,"3":1006,"4":995,"5":991,"6":1000,"7":999,"8":978,"9":971,"10":966,"11":949,"12":938,"13":940,"14":933,"15":937,"16":936,"17":925,"18":935,"19":941,"20":921,"21":935,"22":937,"23":927,"24":929,"25":953,"26":989,"27":1016,"28":1065,"29":1116,"30":1178,"31":1222,"32":1252,"33":1315,"34":1353,"35":1394},"["群益中國新機會基金-新臺幣"]":{"0":2593,"1":3191,"2":3384,"3":3322,"4":2749,"5":3101,"6":3241,"7":3343,"8":3321,"9":2721,"10":3162,"11":3077,"12":2984,"13":2893,"14":2910,"15":2905,"16":2872,"17":2796,"18":2698,"19":2580,"20":2077,"21":2061,"22":2455,"23":2350,"24":2317,"25":2330,"26":2405,"27":2492,"28":2526,"29":2554,"30":2707,"31":2762,"32":2886,"33":2854,"34":2826,"35":2754},"["兆豐國際中國A股基金(美金)"]":{"0":15,"1":14,"2":12,"3":12,"4":11,"5":11,"6":11,"7":11,"8":9,"9":10,"10":9,"11":10,"12":10,"13":10,"14":10,"15":10,"16":10,"17":10,"18":10,"19":9,"20":9,"21":8,"22":9,"23":9,"24":9,"25":10,"26":11,"27":10,"28":11,"29":9,"30":11,"31":14,"32":16,"33":16,"34":19,"35":20},"["台新中國精選中小基金"]":{"0":176,"1":183,"2":179,"3":167,"4":170,"5":169,"6":176,"7":187,"8":183,"9":180,"10":181,"11":172,"12":167,"13":169,"14":167,"15":159,"16":162,"17":169,"18":166,"19":161,"20":159,"21":135,"22":162,"23":158,"24":160,"25":157,"26":154,"27":154,"28":156,"29":158,"30":159,"31":160,"32":161,"33":160,"34":160,"35":158}}

In [37]:
df_india=df[result_id['India']]
df_india.columns = [result_n['India']]
df_india
f = open('india.json','w')
f.write(df_india.to_json(force_ascii=False))
f.close()

In [39]:
df_russia=df[result_id['Russia']]
df_russia.columns = [result_n['Russia']]
df_russia
f = open('russia.json','w')
f.write(df_russia.to_json(force_ascii=False))
f.close()

In [38]:
df_brazil=df[result_id['Brazil']]
df_brazil.columns = [result_n['Brazil']]
f = open('brazil.json','w')
f.write(df_brazil.to_json(force_ascii=False))
f.close()

In [80]:
f = open('russia_percentage.json','w')
f.write(russia_sip_money.to_json(force_ascii=False))
f.close()

In [81]:
f = open('india_percentage.json','w')
f.write(india_sip_money.to_json(force_ascii=False))
f.close()

In [82]:
f = open('brazil_percentage.json','w')
f.write(brazil_sip_money.to_json(force_ascii=False))
f.close()

In [83]:
f = open('china_percentage.json','w')
f.write(china_sip_money.to_json(force_ascii=False))
f.close()

In [ ]:
pd.set_option('display.max_rows', None)
df2 = pd.read_html("https://www.moneydj.com/funddj/yb/YP302000.djhtm?a=ET003001")
df3 = pd.read_html("https://www.moneydj.com/funddj/yb/yp302000.djhtm?a=ET003002")
df4 = pd.read_html("https://www.moneydj.com/funddj/yb/yp302000.djhtm?a=ET003003")
dfFinal = pd.concat([df2[4], df3[4], df4[4]], axis=0)
dfFinal

In [ ]:
for name in newAliveList:
    filterName = (dfFinal["基金名稱"]["基金名稱"] == name)
    try:
        print(dfFinal[filterName]["報酬率(%)"]["六個月"].values[0])
    except:
        print(name)